#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Run and plot subproblem strategy ablations for case3lite/case118.

The script reuses the existing subproblem-BCD entrypoint parameters, then runs
two variants by default:

* method: current configured method.
* no_strategy: original-style baseline with strategy aids disabled.

Each run still uses ``run_training``'s built-in ``TrainingLogger``.  The metrics
JSON generated by ``run_training`` is copied into a dedicated experiment
directory, and aggregate comparison figures are written after all requested
runs complete.
"""

from __future__ import annotations

import argparse
import csv
import importlib
import json
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


DEFAULT_CASES = ("case3lite", "case118")
DEFAULT_VARIANTS = ("method", "no_strategy")
DEFAULT_PLOT_TEST_SAMPLES = 20
DEFAULT_PLOT_TEST_MAX_ITER = 60


@dataclass(frozen=True)
class RunSpec:
    case: str
    variant: str

    @property
    def slug(self) -> str:
        return f"{self.case}_{self.variant}"


def _parse_csv(text: str | None) -> list[str] | None:
    if text is None:
        return None
    items = [x.strip() for x in str(text).split(",") if x.strip()]
    return items or None


def _parse_units(text: str | None) -> list[int] | None:
    items = _parse_csv(text)
    if not items:
        return None
    return [int(x) for x in items]


def _abs(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else (ROOT / p).resolve()


def _reload_training_modules():
    import run_training as rt

    rt = importlib.reload(rt)
    import run_training_case118 as case118_cfg

    case118_cfg = importlib.reload(case118_cfg)
    case118_cfg.rt = rt
    return rt, case118_cfg


def _set_common_safety(rt) -> None:
    rt.MODE = "surrogate"
    rt.RUN_FP = False
    rt.ENABLE_SPARSE_SUPPORTS = False
    rt.SURROGATE_MODEL_DIR = None
    rt.SURROGATE_CONTINUE_TRAINING = False
    rt.SURROGATE_DUAL_PREDICTOR_ONLY = False


def _configure_case3lite(rt, args: argparse.Namespace) -> None:
    _set_common_safety(rt)
    rt.CASE_NAME = "case3lite"
    rt.SURROGATE_CONSTRAINT_STRATEGY = "all_templates_sign4_plus_single"
    rt.USE_UNIT_PREDICTOR = True
    rt.UNIT_PREDICTOR_LOAD_PATH = None
    rt.UNIT_PREDICTOR_AUTO_LATEST_STANDALONE = True
    rt.UNIT_PREDICTOR_LOAD_METADATA_CONFIG = True

    if args.case3lite_active_set:
        rt.ACTIVE_SETS_FILE = str(_abs(args.case3lite_active_set))
    if args.case3lite_units is not None:
        rt.UNIT_IDS = list(args.case3lite_units)
    if args.case3lite_max_samples is not None:
        rt.MAX_SAMPLES = max(1, int(args.case3lite_max_samples))
    if args.case3lite_max_iter is not None:
        n = max(1, int(args.case3lite_max_iter))
        rt.MAX_ITER = n
        rt.SUBPROBLEM_MAX_ITER = n
        rt.SUBPROBLEM_PREDICTOR_WARMUP_ROUNDS = max(0, round(n * 0.10))
        rt.SUBPROBLEM_MU_DUAL_FLOOR_INDIVIDUAL_ROUND = max(0, round(n * 0.25))
        rt.SUBPROBLEM_MU_DUAL_FLOOR_DECAY_ROUND = max(0, round(n * 0.50))
        rt.SUBPROBLEM_PG_COST_START_ROUND = max(0, n // 4)
    if args.case3lite_backend is not None:
        rt.SUBPROBLEM_LP_BACKEND = args.case3lite_backend
    if args.sample_workers is not None:
        w = max(1, int(args.sample_workers))
        rt.N_WORKERS_SAMPLE = w
        rt.N_WORKERS_SUBPROBLEM = w
    if args.unit_workers is not None:
        rt.N_WORKERS_UNIT = max(1, int(args.unit_workers))


def _configure_case118(rt, case118_cfg, args: argparse.Namespace) -> None:
    case118_cfg.TRAIN_TARGET = "subproblem_bcd"
    case118_cfg.SUBPROBLEM_SOLVE_PRESET = args.case118_preset

    if args.case118_active_set:
        active = _abs(args.case118_active_set)
        try:
            case118_cfg.CASE118_ACTIVE_SET_JSON = str(active.relative_to(ROOT))
        except ValueError:
            case118_cfg.CASE118_ACTIVE_SET_JSON = str(active)
    if args.case118_units is not None:
        case118_cfg.CASE118_SUBPROBLEM_UNIT_IDS = list(args.case118_units)
    if args.case118_max_samples is not None:
        case118_cfg.SUBPROBLEM_LIGHT_MAX_SAMPLES = max(1, int(args.case118_max_samples))
    if args.case118_max_iter is not None:
        case118_cfg.SUBPROBLEM_LIGHT_MAX_ITER = max(1, int(args.case118_max_iter))
    if args.sample_workers is not None:
        case118_cfg.SUBPROBLEM_LIGHT_N_WORKERS_SAMPLE = max(1, int(args.sample_workers))
    if args.unit_workers is not None:
        case118_cfg.SUBPROBLEM_LIGHT_N_WORKERS_UNIT = max(1, int(args.unit_workers))

    case118_cfg._validate_inputs()
    case118_cfg._configure_common()
    case118_cfg._configure_subproblem_bcd()
    case118_cfg._apply_subproblem_light_runtime_overrides()


def _apply_no_strategy(rt, *, disable_direct_targets: bool) -> None:
    """Disable strategy aids while preserving the case's base solve/training scale."""
    rt.SURROGATE_CONSTRAINT_STRATEGY = "sensitive"
    rt.USE_UNIT_PREDICTOR = False
    rt.UNIT_PREDICTOR_LOAD_PATH = None
    rt.UNIT_PREDICTOR_AUTO_LATEST_STANDALONE = False
    rt.UNIT_PREDICTOR_UNIT1_EXTRA_TV_EPOCHS = 0
    rt.UNIT_PREDICTOR_AUTO_EXTRA_TV = False

    rt.SUBPROBLEM_MU_DUAL_FLOOR_INIT = 0.0
    rt.SUBPROBLEM_MU_DUAL_FLOOR_INDIVIDUAL_ROUND = 0
    rt.SUBPROBLEM_MU_DUAL_FLOOR_DECAY_ROUND = 0
    rt.SUBPROBLEM_MU_SIGNED_ROUND_INTERVAL = None
    rt.SUBPROBLEM_MU_SIGN_HYSTERESIS_ROUNDS = 0
    rt.SUBPROBLEM_MU_SIGN_FLIP_MIN_SHARE = 1.0
    rt.SUBPROBLEM_X_BOUND_DUAL_ZERO_ROUNDS = 0

    rt.SUBPROBLEM_PREDICTOR_WARMUP_ROUNDS = 0
    rt.SUBPROBLEM_SIGN4_CURRICULUM_ROUNDS = 0
    rt.SUBPROBLEM_SIGN4_INITIAL_SCALE = 1.0
    rt.SUBPROBLEM_SIGN4_FINAL_SCALE = 1.0
    rt.SUBPROBLEM_SIGN4_DELAY_ROUNDS = 0
    rt.SUBPROBLEM_SURROGATE_DELTA_REFERENCE_LIFT = False

    if disable_direct_targets:
        rt.SUBPROBLEM_MAIN_DIRECT_EPOCHS = 0
        rt.SUBPROBLEM_C_PG_DIRECT_EPOCHS = 0


def _resolve_case_config(spec: RunSpec, args: argparse.Namespace):
    rt, case118_cfg = _reload_training_modules()
    if spec.case == "case3lite":
        _configure_case3lite(rt, args)
    elif spec.case == "case118":
        _configure_case118(rt, case118_cfg, args)
    else:
        raise ValueError(f"unsupported case: {spec.case}")

    if spec.variant == "method":
        pass
    elif spec.variant == "no_strategy":
        _apply_no_strategy(
            rt,
            disable_direct_targets=not args.keep_direct_targets_in_baseline,
        )
    else:
        raise ValueError(f"unsupported variant: {spec.variant}")

    return rt


def _config_snapshot(rt, spec: RunSpec) -> dict[str, Any]:
    keys = [
        "CASE_NAME",
        "MODE",
        "ACTIVE_SETS_FILE",
        "MAX_SAMPLES",
        "UNIT_IDS",
        "N_WORKERS_UNIT",
        "N_WORKERS_SAMPLE",
        "SUBPROBLEM_LP_BACKEND",
        "DUAL_EPOCHS",
        "SUBPROBLEM_MAX_ITER",
        "NN_EPOCHS",
        "SURROGATE_CONSTRAINT_STRATEGY",
        "USE_UNIT_PREDICTOR",
        "UNIT_PREDICTOR_LOAD_PATH",
        "UNIT_PREDICTOR_AUTO_LATEST_STANDALONE",
        "SUBPROBLEM_MU_DUAL_FLOOR_INIT",
        "SUBPROBLEM_MU_DUAL_FLOOR_INDIVIDUAL_ROUND",
        "SUBPROBLEM_MU_DUAL_FLOOR_DECAY_ROUND",
        "SUBPROBLEM_MU_SIGNED_ROUND_INTERVAL",
        "SUBPROBLEM_PREDICTOR_WARMUP_ROUNDS",
        "SUBPROBLEM_SIGN4_CURRICULUM_ROUNDS",
        "SUBPROBLEM_SIGN4_INITIAL_SCALE",
        "SUBPROBLEM_SIGN4_FINAL_SCALE",
        "SUBPROBLEM_SIGN4_DELAY_ROUNDS",
        "SUBPROBLEM_SURROGATE_DELTA_REFERENCE_LIFT",
        "SUBPROBLEM_MAIN_DIRECT_EPOCHS",
        "SUBPROBLEM_C_PG_DIRECT_EPOCHS",
    ]
    snap = {"case": spec.case, "variant": spec.variant}
    for key in keys:
        value = getattr(rt, key, None)
        if isinstance(value, Path):
            value = str(value)
        snap[key] = value
    return snap


def _metrics_files(case: str) -> set[Path]:
    return set((ROOT / "result").glob(f"training_metrics_{case}_*.json"))


def _run_one(spec: RunSpec, args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    rt = _resolve_case_config(spec, args)
    config = _config_snapshot(rt, spec)
    if args.dry_run:
        print(f"[dry-run] {spec.slug}: {json.dumps(config, ensure_ascii=False)}", flush=True)
        return {"spec": spec.__dict__, "config": config, "metrics_json": None}

    before = _metrics_files(spec.case)
    print(f"[run] {spec.slug}", flush=True)
    rt.main()
    new_files = sorted(
        _metrics_files(spec.case) - before,
        key=lambda p: p.stat().st_mtime,
    )
    if not new_files:
        raise RuntimeError(f"run_training did not create a metrics JSON for {spec.slug}")

    src = new_files[-1]
    dst = out_dir / f"metrics_{spec.slug}.json"
    shutil.copy2(src, dst)
    print(f"[run] {spec.slug} metrics: {dst}", flush=True)
    return {
        "spec": spec.__dict__,
        "config": config,
        "metrics_json": str(dst),
        "source_metrics_json": str(src),
    }


def _load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _aggregate_surrogate_metrics(data: dict[str, Any]) -> list[dict[str, float]]:
    surrogate = data.get("metrics", {}).get("surrogate", {})
    by_iter: dict[int, dict[str, list[float]]] = {}
    if not isinstance(surrogate, dict):
        return []
    for records in surrogate.values():
        if not isinstance(records, list):
            continue
        for record in records:
            if not isinstance(record, dict) or "iter" not in record:
                continue
            it = int(record["iter"])
            bucket = by_iter.setdefault(it, {})
            for key, value in record.items():
                if key == "iter":
                    continue
                if isinstance(value, (int, float)) and value == value:
                    bucket.setdefault(key, []).append(float(value))

    rows: list[dict[str, float]] = []
    for it in sorted(by_iter):
        row: dict[str, float] = {"iter": float(it)}
        for key, values in by_iter[it].items():
            if values:
                row[key] = sum(values) / len(values)
        if "obj_primal" in row and "obj_dual" in row and "obj_opt" in row:
            row["obj_total"] = row["obj_primal"] + row["obj_dual"] + row["obj_opt"]
        rows.append(row)
    return rows


def _write_summary_csv(summary_rows: list[dict[str, Any]], path: Path) -> None:
    if not summary_rows:
        return
    fieldnames = [
        "case",
        "variant",
        "iter",
        "obj_total",
        "obj_primal",
        "obj_dual",
        "obj_dual_pg",
        "obj_dual_x",
        "obj_opt",
        "nn_loss",
        "mu_mean",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in summary_rows:
            writer.writerow({key: row.get(key) for key in fieldnames})


def _plot_comparisons(results: list[dict[str, Any]], out_dir: Path) -> list[str]:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except Exception as exc:
        print(f"[plot] skipped: matplotlib unavailable ({exc})", flush=True)
        return []

    series: dict[tuple[str, str], list[dict[str, float]]] = {}
    summary_rows: list[dict[str, Any]] = []
    for result in results:
        metrics_path_text = result.get("metrics_json")
        if not metrics_path_text:
            continue
        spec = result["spec"]
        rows = _aggregate_surrogate_metrics(_load_json(Path(metrics_path_text)))
        series[(spec["case"], spec["variant"])] = rows
        if rows:
            final = dict(rows[-1])
            final["case"] = spec["case"]
            final["variant"] = spec["variant"]
            summary_rows.append(final)

    _write_summary_csv(summary_rows, out_dir / "comparison_summary.csv")
    with (out_dir / "comparison_summary.json").open("w", encoding="utf-8") as f:
        json.dump(summary_rows, f, ensure_ascii=False, indent=2)

    written: list[str] = []
    cases = sorted({case for case, _variant in series})
    metric_specs = [
        ("obj_total", "Total objective residual"),
        ("obj_primal", "Primal residual"),
        ("obj_dual", "Dual residual"),
        ("obj_opt", "Optimality residual"),
        ("nn_loss", "NN loss"),
        ("mu_mean", "Mean mu"),
    ]
    colors = {"method": "#2166ac", "no_strategy": "#d6604d"}
    labels = {"method": "method", "no_strategy": "no strategy"}

    for case in cases:
        fig, axes = plt.subplots(2, 3, figsize=(13.2, 7.2), squeeze=False)
        for ax, (metric, title) in zip(axes.flat, metric_specs):
            plotted = False
            for variant in DEFAULT_VARIANTS:
                rows = series.get((case, variant), [])
                rows = [row for row in rows if metric in row]
                if not rows:
                    continue
                x = np.array([row["iter"] + 1 for row in rows], dtype=float)
                y = np.array([row[metric] for row in rows], dtype=float)
                if metric.startswith("obj"):
                    y = np.log10(np.maximum(y, 1e-15))
                    ax.set_ylabel("log10(value)")
                else:
                    ax.set_ylabel("value")
                ax.plot(
                    x,
                    y,
                    marker="o",
                    markersize=3,
                    linewidth=1.6,
                    color=colors.get(variant),
                    label=labels.get(variant, variant),
                )
                plotted = True
            ax.set_title(title, loc="left", fontsize=10)
            ax.set_xlabel("BCD iteration")
            ax.grid(True, alpha=0.3, linestyle="--")
            if plotted:
                ax.legend(fontsize=8)
            else:
                ax.text(0.5, 0.5, "No data", ha="center", va="center", transform=ax.transAxes)

        fig.suptitle(f"Subproblem strategy ablation: {case}", fontsize=13, fontweight="bold")
        fig.tight_layout()
        png = out_dir / f"compare_{case}.png"
        pdf = out_dir / f"compare_{case}.pdf"
        fig.savefig(png, dpi=300, bbox_inches="tight")
        fig.savefig(pdf, dpi=300, bbox_inches="tight")
        plt.close(fig)
        written.extend([str(png), str(pdf)])
        print(f"[plot] wrote {png}", flush=True)

    return written


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cases", default=",".join(DEFAULT_CASES), help="Comma-separated cases.")
    p.add_argument(
        "--variants",
        default=",".join(DEFAULT_VARIANTS),
        help="Comma-separated variants: method,no_strategy.",
    )
    p.add_argument("--output-dir", default="result/subproblem_strategy_ablation")
    p.add_argument("--dry-run", action="store_true", help="Print resolved configs without training.")

    p.add_argument("--case3lite-active-set", default=None)
    p.add_argument("--case3lite-units", type=_parse_units, default=None)
    p.add_argument(
        "--case3lite-max-samples",
        type=int,
        default=DEFAULT_PLOT_TEST_SAMPLES,
        help=f"Samples used by case3lite runs. Default: {DEFAULT_PLOT_TEST_SAMPLES}.",
    )
    p.add_argument(
        "--case3lite-max-iter",
        type=int,
        default=DEFAULT_PLOT_TEST_MAX_ITER,
        help=f"Subproblem BCD iterations for case3lite. Default: {DEFAULT_PLOT_TEST_MAX_ITER}.",
    )
    p.add_argument("--case3lite-backend", choices=("gurobi", "cvxpy_highs"), default=None)

    p.add_argument("--case118-active-set", default=None)
    p.add_argument("--case118-units", type=_parse_units, default=None)
    p.add_argument(
        "--case118-max-samples",
        type=int,
        default=DEFAULT_PLOT_TEST_SAMPLES,
        help=f"Samples used by case118 runs. Default: {DEFAULT_PLOT_TEST_SAMPLES}.",
    )
    p.add_argument(
        "--case118-max-iter",
        type=int,
        default=DEFAULT_PLOT_TEST_MAX_ITER,
        help=f"Subproblem BCD iterations for case118. Default: {DEFAULT_PLOT_TEST_MAX_ITER}.",
    )
    p.add_argument("--case118-preset", choices=("desktop", "server"), default="desktop")

    p.add_argument("--sample-workers", type=int, default=None)
    p.add_argument("--unit-workers", type=int, default=None)
    p.add_argument(
        "--keep-direct-targets-in-baseline",
        action="store_true",
        help="Do not disable direct-target NN pretraining in the no_strategy baseline.",
    )
    return p


def main() -> None:
    args = _build_parser().parse_args()
    cases = _parse_csv(args.cases) or list(DEFAULT_CASES)
    variants = _parse_csv(args.variants) or list(DEFAULT_VARIANTS)
    specs = [RunSpec(case=case, variant=variant) for case in cases for variant in variants]

    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = _abs(args.output_dir) / f"ablation_{run_id}"
    out_dir.mkdir(parents=True, exist_ok=True)

    results = []
    for spec in specs:
        results.append(_run_one(spec, args, out_dir))

    if not args.dry_run:
        _plot_comparisons(results, out_dir)

    manifest = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "root": str(ROOT),
        "output_dir": str(out_dir),
        "dry_run": bool(args.dry_run),
        "results": results,
    }
    with (out_dir / "manifest.json").open("w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    print(f"[done] manifest: {out_dir / 'manifest.json'}", flush=True)


if __name__ == "__main__":
    main()
